#!/usr/bin/env bash
# Tool Name :- Query-IP
# Author :- David Gregs
# Date :- 23/08/2023

case "$1" in
  -m)
    python3 model/querym.py
  ;;
  -t)
    case "$#" in
    2)
      python3 model/queryip.py $2
    ;;
    *)
      echo "error : invalid arguments !!"
      echo "use: query -t <target_ip>"
    ;;
    esac
  ;;
  -u)
    python3 model/update.py
    exit
  ;;
  update)
    python3 model/update.py
    exit
  ;;
  start)
    python3 model/Query_IP.py
    exit
  ;;
  --rm)
    python3 model/uninstall.py
    exit
  ;;
  --help)
    python3 model/help.py
    exit
  ;;
  *)
    echo "Usage: query [command]... [arguments]..."
    echo " Commands:"
    echo " -t <target_ip>      to query target ip."
    echo " -m                  to query your own ip."
    echo " --help                  to show help."
    echo " -u                  to update Query-IP."
    echo " update              to update Query-IP.."
    echo " start               to start Query-IP. menu."
    echo " --rm                to uninstall Query-IP tool."
esac
