from colorama import Fore, Style

print(Fore.CYAN + "\n\n")
print(Fore.YELLOW + "----------------------------------------------------------------")
print("    " + Fore.CYAN + " ____   _   _   ____   ____  __   __       _   ____ ")
print("    " + Fore.CYAN + "/ __ \\ | | | | / __ \\ |  __| \\ \_/ /      | | |  __ \ ")
print("   " + Fore.CYAN + "| |  | || | | || |__| || |     \\___/       | | | |__| |")
print("   " + Fore.CYAN + "| |  | || | | ||  ____|| |      | |" + Fore.YELLOW + "   ~~" + Fore.CYAN + "   | | |  ____| ")
print("   " + Fore.CYAN + "| |__| |\ \_/ /| |____ | |      | |        | | | |")
print("    " + Fore.CYAN + "\\___\\ \\ \\___/  \\_____||_|      |_|        |_| |_|")
print("    " + Fore.CYAN + "     \\_\\")
print(Fore.YELLOW + "----------------------------------------------------------------")
print("    " + Fore.CYAN + "-------------------------------------------------------")
print("    " + Fore.CYAN + "------------------" + Fore.YELLOW +  "<IP Information>" + Fore.CYAN +   "--------------")
print("    " + Fore.CYAN + "------------------------------------------------")
print("\n\n")
